FROM node:20-alpine

WORKDIR /app

COPY package*.json ./

RUN npm config set fetch-retries 5
RUN npm config set fetch-retry-mintimeout 20000
RUN npm config set fetch-retry-maxtimeout 120000
RUN npm ci

COPY . .

# Build Next.js
RUN npm run build

EXPOSE 3000

# Start Next.js
CMD ["npm", "start"]